name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: setup vagrant repo GPG key
        run: wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg

      - name: setup hashicorp repo
        run: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

      - name: install vagrant
        run: sudo apt update && sudo apt install vagrant

      - name: setup VirtualBox repo GPG key
        run: wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --dearmor --yes --output /usr/share/keyrings/oracle-virtualbox-2016.gpg

      - name: setup VirtualBox repo
        run: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] http://download.virtualbox.org/virtualbox/debian $(. /etc/os-release && echo "$VERSION_CODENAME") contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
        
      - name: install VirtualBox
        run: sudo apt update && sudo apt install virtualbox-7.0

      - name: Show Vagrant version
        run: vagrant --version

      - name: Enable KVM group perms
        run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo cat /etc/udev/rules.d/99kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm
            sudo ls /dev/kvm
      
      - name: Run vagrant up
        run: vagrant up --provider=virtualbox

      - name: ssh into box after boot
        run: vagrant ssh -c "echo 'hello world!'"
